"""
Government Talent & Opportunity Network - Data Models
"""

from enum import StrEnum


class OpportunityType(StrEnum):
    """Types of government opportunities"""
    TRAINER = "TRAINER"
    MENTOR = "MENTOR"
    KNOWLEDGE_SHARING = "KNOWLEDGE_SHARING"
    SUBJECT_MATTER_EXPERT = "SUBJECT_MATTER_EXPERT"
    CAPACITY_BUILDING = "CAPACITY_BUILDING"
    WORKSHOP = "WORKSHOP"
    ADVISORY = "ADVISORY"
    OTHER_APPROVED = "OTHER_APPROVED"


class OpportunityStatus(StrEnum):
    """Opportunity lifecycle status"""
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class VisibilityLevel(StrEnum):
    """Talent profile visibility levels"""
    PRIVATE = "PRIVATE"
    MY_DEPARTMENT = "MY_DEPARTMENT"
    AUTHORIZED_DEPARTMENTS = "AUTHORIZED_DEPARTMENTS"


class TalentAuditAction(StrEnum):
    """Audit log action types"""
    TALENT_PROFILE_VIEWED = "TALENT_PROFILE_VIEWED"
    TALENT_PROFILE_UPDATED = "TALENT_PROFILE_UPDATED"
    TALENT_VISIBILITY_CHANGED = "TALENT_VISIBILITY_CHANGED"
    OPPORTUNITY_CREATED = "OPPORTUNITY_CREATED"
    OPPORTUNITY_UPDATED = "OPPORTUNITY_UPDATED"
    OPPORTUNITY_PUBLISHED = "OPPORTUNITY_PUBLISHED"
    OPPORTUNITY_CLOSED = "OPPORTUNITY_CLOSED"
    OPPORTUNITY_MATCH_REQUESTED = "OPPORTUNITY_MATCH_REQUESTED"
    OPPORTUNITY_MATCHES_VIEWED = "OPPORTUNITY_MATCHES_VIEWED"
