from enum import StrEnum


class Domain(StrEnum):
    STATISTICAL = "STATISTICAL"
    TECHNICAL = "TECHNICAL"
    DIGITAL_GOVERNANCE = "DIGITAL_GOVERNANCE"
    BEHAVIOURAL_MANAGERIAL = "BEHAVIOURAL_MANAGERIAL"


class FrameworkStatus(StrEnum):
    PROTOTYPE = "prototype"
    OFFICIAL = "official"
    DERIVED = "derived"


class SourceType(StrEnum):
    PROTOTYPE = "PROTOTYPE"
    OFFICIAL = "OFFICIAL"
    DERIVED = "DERIVED"


class EvidenceAuthority(StrEnum):
    SUPPORTING = "SUPPORTING"
    AUTHORITATIVE = "AUTHORITATIVE"


class EvidenceType(StrEnum):
    # Supporting evidence
    LEARNING_ACTIVITY = "LEARNING_ACTIVITY"
    LEARNING_COMPLETION = "LEARNING_COMPLETION"
    PRACTICE_QUIZ = "PRACTICE_QUIZ"
    AI_GENERATED_QUIZ = "AI_GENERATED_QUIZ"
    TRAINER_REVIEWED_QUIZ = "TRAINER_REVIEWED_QUIZ"
    QUIZ = "QUIZ"
    TRAINING = "TRAINING"
    SELF_ASSESSMENT = "SELF_ASSESSMENT"

    # Authoritative evidence
    FORMAL_CAPABILITY_ASSESSMENT = "FORMAL_CAPABILITY_ASSESSMENT"
    ADAPTIVE_CAPABILITY_ASSESSMENT = "ADAPTIVE_CAPABILITY_ASSESSMENT"
    CAPABILITY_ASSESSMENT = "CAPABILITY_ASSESSMENT"
    KNOWLEDGE_TEST = "KNOWLEDGE_TEST"
    SCENARIO_TEST = "SCENARIO_TEST"
    BASELINE_ASSESSMENT = "BASELINE_ASSESSMENT"


AUTHORITATIVE_EVIDENCE_TYPES: set[str] = {
    EvidenceType.FORMAL_CAPABILITY_ASSESSMENT,
    EvidenceType.ADAPTIVE_CAPABILITY_ASSESSMENT,
    EvidenceType.CAPABILITY_ASSESSMENT,
    EvidenceType.KNOWLEDGE_TEST,
    EvidenceType.SCENARIO_TEST,
    EvidenceType.BASELINE_ASSESSMENT,
}

AUTHORITATIVE_CONFIDENCE: float = 0.85
SUPPORTING_CONFIDENCE: float = 0.30
